language: node_js
node_js:
- '8'
before_install:
install:
- npm i
- cd ui && npm i && cd ..
cache:
  directories:
  - node_modules
  - ui/node_modules
script:
  - cd ui && npm run build && cd ..
  - npm run deploy